stages:
  baumgartner_etl:
    cmd: python src/etl_baumgartner_suzuki.py data/baumgartner_suzuki/c8re00032h2.xlsx
      data/baumgartner_suzuki/
    deps:
    - data/baumgartner_suzuki/c8re00032h2.xlsx
    - src/etl_baumgartner_suzuki.py
    outs:
    - data/baumgartner_suzuki/baumgartner_suzuki-minlp1-optimization.pb
    - data/baumgartner_suzuki/warnings_baumgartner_suzuki-minlp1-optimization.json
    - data/baumgartner_suzuki/baumgartner_suzuki-minlp2-optimization.pb
    - data/baumgartner_suzuki/warnings_baumgartner_suzuki-minlp2-optimization.json