stages:
  baumgartner_etl:
    desc: "Convert excel file into ORD schema"
    cmd: python multitask/etl_baumgartner_suzuki.py data/baumgartner_suzuki/c8re00032h2.xlsx
      data/baumgartner_suzuki/ord
    deps:
      - data/baumgartner_suzuki/c8re00032h2.xlsx
      - multitask/etl_baumgartner_suzuki.py
    outs:
      - data/baumgartner_suzuki/ord/

  reizman_etl:
    desc: "Convert Reizman data to ORD schema"
    cmd: python multitask/etl_reizman_suzuki.py data/reizman_suzuki/ data/reizman_suzuki/ord/
    deps:
      - data/reizman_suzuki/reizman_suzuki_case_1.csv
      - data/reizman_suzuki/reizman_suzuki_case_2.csv
      - data/reizman_suzuki/reizman_suzuki_case_3.csv
      - data/reizman_suzuki/reizman_suzuki_case_4.csv
      - multitask/etl_reizman_suzuki.py
    outs:
      - data/reizman_suzuki/ord/

  baumgartner_suzuki_benchmark_training:
    desc: "Train a benchmark based on data in the ORD schema format"
    cmd: >-
      python multitask/suzuki_benchmark_training.py
      baumgartner_suzuki
      data/baumgartner_suzuki/ord data/reizman_suzuki/ord
      data/baumgartner_suzuki/emulator
      figures/
      --${suzuki_benchmark_training.split-catalyst}
      --max-epochs ${suzuki_benchmark_training.max-epochs}
      --cv-folds ${suzuki_benchmark_training.cv-folds}
      --verbose ${suzuki_benchmark_training.verbose}
      --${suzuki_benchmark_training.include-reactant-concentrations}
      --no-print-warnings
    deps:
      - multitask/suzuki_benchmark_training.py
      - data/baumgartner_suzuki/ord/
      - data/reizman_suzuki/ord
    outs:
    - data/baumgartner_suzuki/emulator/
    - figures/baumgartner_suzuki_parity_plot.png

  reizman_suzuki_benchmark_training:
    foreach: # cases
      - 1
      - 2
      - 3
      - 4
    do:
      desc: "Train a benchmark based on data in the ORD schema format"
      cmd: >-
        python multitask/suzuki_benchmark_training.py
        reizman_suzuki_case_${item}
        data/baumgartner_suzuki/ord data/reizman_suzuki/ord
        data/reizman_suzuki/emulator_case_${item}/
        figures/
        --${suzuki_benchmark_training.split-catalyst}
        --max-epochs ${suzuki_benchmark_training.max-epochs}
        --cv-folds ${suzuki_benchmark_training.cv-folds}
        --verbose ${suzuki_benchmark_training.verbose}
        --no-print-warnings
      deps:
        - multitask/suzuki_benchmark_training.py
        - data/baumgartner_suzuki/ord/
        - data/reizman_suzuki/ord
      outs:
        - data/reizman_suzuki/emulator_case_${item}/
        - figures/reizman_suzuki_case_${item}_parity_plot.png