suzuki_benchmark_training:
  cv-folds: 5
  include-reactant-concentrations: no-include-reactant-concentrations
  max-epochs: 1000
  split-catalyst: no-split-catalyst
  verbose: 0
suzuki_one_experiments:
  baumgartner_suzuki_cotrain_reizman_suzuki_case_1:
    benchmark: data/baumgartner_suzuki/emulator
    dataset_1: data/reizman_suzuki/ord/reizman_suzuki_case_1.pb
    model_name: baumgartner_suzuki
  baumgartner_suzuki_cotrain_reizman_suzuki_case_2:
    benchmark: data/baumgartner_suzuki/emulator
    dataset_1: data/reizman_suzuki/ord/reizman_suzuki_case_2.pb
    model_name: baumgartner_suzuki
  baumgartner_suzuki_cotrain_reizman_suzuki_case_3:
    benchmark: data/baumgartner_suzuki/emulator
    dataset_1: data/reizman_suzuki/ord/reizman_suzuki_case_3.pb
    model_name: baumgartner_suzuki
  baumgartner_suzuki_cotrain_reizman_suzuki_case_4:
    benchmark: data/baumgartner_suzuki/emulator
    dataset_1: data/reizman_suzuki/ord/reizman_suzuki_case_4.pb
    model_name: baumgartner_suzuki
  reizman_suzuki_1_cotrain_baumgartner_suzuki:
    benchmark: data/reizman_suzuki/emulator_case_1
    dataset_1: data/baumgartner_suzuki/ord/baumgartner_suzuki.pb
    model_name: reizman_suzuki_case_1
  reizman_suzuki_2_cotrain_baumgartner_suzuki:
    benchmark: data/reizman_suzuki/emulator_case_2
    dataset_1: data/baumgartner_suzuki/ord/baumgartner_suzuki.pb
    model_name: reizman_suzuki_case_2
  reizman_suzuki_3_cotrain_baumgartner_suzuki:
    benchmark: data/reizman_suzuki/emulator_case_3
    dataset_1: data/baumgartner_suzuki/ord/baumgartner_suzuki.pb
    model_name: reizman_suzuki_case_3
  reizman_suzuki_4_cotrain_baumgartner_suzuki:
    benchmark: data/reizman_suzuki/emulator_case_4
    dataset_1: data/baumgartner_suzuki/ord/baumgartner_suzuki.pb
    model_name: reizman_suzuki_case_4
  reizman_suzuki_case_1_cotrain_reizman_suzuki_case_2:
    benchmark: data/reizman_suzuki/emulator_case_1
    dataset_1: data/reizman_suzuki/ord/reizman_suzuki_case_2.pb
    model_name: reizman_suzuki_case_1
  reizman_suzuki_case_1_cotrain_reizman_suzuki_case_3:
    benchmark: data/reizman_suzuki/emulator_case_1
    dataset_1: data/reizman_suzuki/ord/reizman_suzuki_case_3.pb
    model_name: reizman_suzuki_case_1
  reizman_suzuki_case_1_cotrain_reizman_suzuki_case_4:
    benchmark: data/reizman_suzuki/emulator_case_1
    dataset_1: data/reizman_suzuki/ord/reizman_suzuki_case_4.pb
    model_name: reizman_suzuki_case_1
  reizman_suzuki_case_2_cotrain_reizman_suzuki_case_1:
    benchmark: data/reizman_suzuki/emulator_case_2
    dataset_1: data/reizman_suzuki/ord/reizman_suzuki_case_1.pb
    model_name: reizman_suzuki_case_2
  reizman_suzuki_case_2_cotrain_reizman_suzuki_case_3:
    benchmark: data/reizman_suzuki/emulator_case_2
    dataset_1: data/reizman_suzuki/ord/reizman_suzuki_case_3.pb
    model_name: reizman_suzuki_case_2
  reizman_suzuki_case_2_cotrain_reizman_suzuki_case_4:
    benchmark: data/reizman_suzuki/emulator_case_2
    dataset_1: data/reizman_suzuki/ord/reizman_suzuki_case_4.pb
    model_name: reizman_suzuki_case_2
  reizman_suzuki_case_3_cotrain_reizman_suzuki_case_1:
    benchmark: data/reizman_suzuki/emulator_case_3
    dataset_1: data/reizman_suzuki/ord/reizman_suzuki_case_1.pb
    model_name: reizman_suzuki_case_3
  reizman_suzuki_case_3_cotrain_reizman_suzuki_case_2:
    benchmark: data/reizman_suzuki/emulator_case_3
    dataset_1: data/reizman_suzuki/ord/reizman_suzuki_case_2.pb
    model_name: reizman_suzuki_case_3
  reizman_suzuki_case_3_cotrain_reizman_suzuki_case_4:
    benchmark: data/reizman_suzuki/emulator_case_3
    dataset_1: data/reizman_suzuki/ord/reizman_suzuki_case_4.pb
    model_name: reizman_suzuki_case_3
  reizman_suzuki_case_4_cotrain_reizman_suzuki_case_1:
    benchmark: data/reizman_suzuki/emulator_case_4
    dataset_1: data/reizman_suzuki/ord/reizman_suzuki_case_1.pb
    model_name: reizman_suzuki_case_4
  reizman_suzuki_case_4_cotrain_reizman_suzuki_case_2:
    benchmark: data/reizman_suzuki/emulator_case_4
    dataset_1: data/reizman_suzuki/ord/reizman_suzuki_case_2.pb
    model_name: reizman_suzuki_case_4
  reizman_suzuki_case_4_cotrain_reizman_suzuki_case_3:
    benchmark: data/reizman_suzuki/emulator_case_4
    dataset_1: data/reizman_suzuki/ord/reizman_suzuki_case_3.pb
    model_name: reizman_suzuki_case_4
suzuki_optimization:
  batch-size: 1
  max-experiments: 20
  repeats: 20
